#!/usr/bin/env bash
set -u

project_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$project_root" || exit 1

generated_at="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

run_check() {
  local name="$1"
  local cmd="$2"
  local started
  local ended
  started="$(date +%s)"
  if bash -lc "$cmd" >/tmp/skyfi-status-"$name".log 2>&1; then
    ended="$(date +%s)"
    echo "| $name | PASS | $(((ended - started) * 1000)) |"
    return 0
  fi
  ended="$(date +%s)"
  echo "| $name | FAIL | $(((ended - started) * 1000)) |"
  return 1
}

overall="GREEN"

typecheck_row="$(run_check "Typecheck" "npm run typecheck --silent")" || overall="RED"
lint_row="$(run_check "Lint" "npm run lint --silent")" || overall="RED"
test_row="$(run_check "Tests" "npm test --silent")" || overall="RED"

tests_line="$(awk '/Tests[[:space:]]+[0-9]+[[:space:]]+passed/ {print $0}' /tmp/skyfi-status-Tests.log | head -n 1)"
if [ -z "$tests_line" ]; then
  tests_line="Tests count unavailable"
fi

cat >"mcp-docs/STATUS.md" <<EOF
# Reliability Scorecard

Generated: $generated_at

Overall status: **$overall**

| Check | Result | Duration (ms) |
|-------|--------|---------------|
$typecheck_row
$lint_row
$test_row

## Snapshot

- $tests_line
- Command for full gate: \`npm run check\`

## Notes

- Generated by \`scripts/generate-status.sh\`
- Refresh with \`npm run status:refresh\`
EOF

echo "Wrote mcp-docs/STATUS.md"
